# Basic Math and Statistics
## Segment 1 - Using NumPy to perform arithmetic operations on data

In [2]:
import numpy as np
from numpy.random import randn

In [3]:
# Sets the precision of returned decimal / float values
np.set_printoptions(precision=2)

## Creating arrays
### Creating arrays using a list

In [4]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([[10, 20, 30], [40, 50, 60]])

In [8]:
a

array([1, 2, 3, 4, 5, 6])

In [9]:
b

array([[10, 20, 30],
       [40, 50, 60]])

### Creating arrays via assignment

In [ ]:
# Makes the random numbers generated predictable
np.random.seed(25)

In [20]:
c = randn(6)
c

array([ 0.73, -0.22, -1.62,  0.31, -1.16,  0.31])

In [21]:
# the arange method can be used to generate a sequence
# note that the the sequence does include the first number but does not include the last number
d = np.arange(1,36)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35])

## Performing arthimetic on arrays

In [22]:
a * 10

array([10, 20, 30, 40, 50, 60])

In [26]:
# Adds the corresponding values at each index together
# i.e. c[0] = 0.73, a[0] = 1 so result for that index is 1.73
c + a

array([1.73, 1.78, 1.38, 4.31, 3.84, 6.31])

In [28]:
# subtracts the corresponding values at each index from one another
# i.e. c[1] = -0.22, a[1] = 2 so result for that index is -0.44
c * a

array([ 0.73, -0.44, -4.87,  1.25, -5.8 ,  1.88])

In [30]:
# divides the corresponding values at each index
# i.e. c[1] = -0.22, a[1] = 2 so result for that index is -0.11
c / a

array([ 0.73, -0.11, -0.54,  0.08, -0.23,  0.05])

### Multiplying matrices and basic linear algebra

In [31]:
aa = np.array([[2.0, 4.0, 6.0], [1.0, 3.0, 5.0], [10, 20, 30]])
aa

array([[ 2.,  4.,  6.],
       [ 1.,  3.,  5.],
       [10., 20., 30.]])

In [33]:
bb = np.array([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
bb

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [35]:
# Multiplies each element in a matrix by its corresponding element (value at same index) in the other matrix
aa*bb

array([[  0.,   4.,  12.],
       [  3.,  12.,  25.],
       [ 60., 140., 240.]])

In [39]:
# We can also find the dot product of two matrices using the dot() method
# The first returned cell (matrix[0][0] == 48) is calculated by multiplying the first row by the first column and summing
# e.g. (2x0) + (4x3) + (6x6) = 48
# second returned cell (matrix[0][1] == 60) is clacluated like: (2x1) + (4x4) + (6x7) = 60
np.dot(aa,bb)

array([[ 48.,  60.,  72.],
       [ 39.,  48.,  57.],
       [240., 300., 360.]])